//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agunan
    {
        public string Agunan_ID { get; set; }
        public string Account_No { get; set; }
        public string ID_Customer { get; set; }
        public string Type { get; set; }
        public string Amount { get; set; }
    }
}
