//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasCrud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KopinakiEntities : DbContext
    {
        public KopinakiEntities()
            : base("name=KopinakiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agunan> Agunans { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Funding> Fundings { get; set; }
        public virtual DbSet<Lending> Lendings { get; set; }
    
        public virtual ObjectResult<spCollectLendingFundingSum_Result> spCollectLendingFundingSum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCollectLendingFundingSum_Result>("spCollectLendingFundingSum");
        }
    }
}
